// Code generated by protoc-gen-go. DO NOT EDIT.
// source: banner_resource.proto

package v1

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 请求列表
type BannerListReq struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BannerListReq) Reset()         { *m = BannerListReq{} }
func (m *BannerListReq) String() string { return proto.CompactTextString(m) }
func (*BannerListReq) ProtoMessage()    {}
func (*BannerListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fbad0d2a18bc032, []int{0}
}

func (m *BannerListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BannerListReq.Unmarshal(m, b)
}
func (m *BannerListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BannerListReq.Marshal(b, m, deterministic)
}
func (m *BannerListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BannerListReq.Merge(m, src)
}
func (m *BannerListReq) XXX_Size() int {
	return xxx_messageInfo_BannerListReq.Size(m)
}
func (m *BannerListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BannerListReq.DiscardUnknown(m)
}

var xxx_messageInfo_BannerListReq proto.InternalMessageInfo

func (m *BannerListReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *BannerListReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

// 返回资源列表
type BannerListResp struct {
	CurrentPage          int32                  `protobuf:"varint,1,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	TotalCount           int32                  `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	List                 []*BannerListResp_List `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BannerListResp) Reset()         { *m = BannerListResp{} }
func (m *BannerListResp) String() string { return proto.CompactTextString(m) }
func (*BannerListResp) ProtoMessage()    {}
func (*BannerListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fbad0d2a18bc032, []int{1}
}

func (m *BannerListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BannerListResp.Unmarshal(m, b)
}
func (m *BannerListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BannerListResp.Marshal(b, m, deterministic)
}
func (m *BannerListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BannerListResp.Merge(m, src)
}
func (m *BannerListResp) XXX_Size() int {
	return xxx_messageInfo_BannerListResp.Size(m)
}
func (m *BannerListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BannerListResp.DiscardUnknown(m)
}

var xxx_messageInfo_BannerListResp proto.InternalMessageInfo

func (m *BannerListResp) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *BannerListResp) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *BannerListResp) GetList() []*BannerListResp_List {
	if m != nil {
		return m.List
	}
	return nil
}

type BannerListResp_List struct {
	Pic                  string   `protobuf:"bytes,1,opt,name=pic,proto3" json:"pic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BannerListResp_List) Reset()         { *m = BannerListResp_List{} }
func (m *BannerListResp_List) String() string { return proto.CompactTextString(m) }
func (*BannerListResp_List) ProtoMessage()    {}
func (*BannerListResp_List) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fbad0d2a18bc032, []int{1, 0}
}

func (m *BannerListResp_List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BannerListResp_List.Unmarshal(m, b)
}
func (m *BannerListResp_List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BannerListResp_List.Marshal(b, m, deterministic)
}
func (m *BannerListResp_List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BannerListResp_List.Merge(m, src)
}
func (m *BannerListResp_List) XXX_Size() int {
	return xxx_messageInfo_BannerListResp_List.Size(m)
}
func (m *BannerListResp_List) XXX_DiscardUnknown() {
	xxx_messageInfo_BannerListResp_List.DiscardUnknown(m)
}

var xxx_messageInfo_BannerListResp_List proto.InternalMessageInfo

func (m *BannerListResp_List) GetPic() string {
	if m != nil {
		return m.Pic
	}
	return ""
}

func init() {
	proto.RegisterType((*BannerListReq)(nil), "live.resource.v1.BannerListReq")
	proto.RegisterType((*BannerListResp)(nil), "live.resource.v1.BannerListResp")
	proto.RegisterType((*BannerListResp_List)(nil), "live.resource.v1.BannerListResp.List")
}

func init() { proto.RegisterFile("banner_resource.proto", fileDescriptor_9fbad0d2a18bc032) }

var fileDescriptor_9fbad0d2a18bc032 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x55, 0xdb, 0x00, 0xad, 0x2b, 0x4a, 0x65, 0x81, 0x54, 0xba, 0xb8, 0x04, 0x21, 0x75, 0xc1,
	0x55, 0xca, 0xc6, 0x98, 0x4e, 0x48, 0x0c, 0xc8, 0x6c, 0x30, 0x54, 0x49, 0xe4, 0x06, 0x4b, 0x69,
	0x9c, 0x3a, 0x4e, 0x06, 0xfe, 0x2a, 0x92, 0x7f, 0x40, 0xc6, 0xfe, 0x02, 0xe4, 0x23, 0x80, 0x61,
	0x80, 0xe5, 0xfc, 0xde, 0xbb, 0x8f, 0x77, 0xb6, 0xd1, 0x59, 0x1c, 0xe5, 0x39, 0x57, 0x6b, 0xc5,
	0x4b, 0x59, 0xa9, 0x84, 0xd3, 0x42, 0x49, 0x2d, 0xf1, 0x38, 0x13, 0x35, 0xa7, 0x5f, 0x62, 0x1d,
	0x4c, 0xaf, 0x53, 0xa1, 0x5f, 0xaa, 0x98, 0x26, 0x72, 0xbb, 0x48, 0x65, 0x2a, 0x17, 0x50, 0x18,
	0x57, 0x1b, 0x60, 0x40, 0x00, 0x7d, 0x0c, 0xf0, 0x53, 0x74, 0x1c, 0xc2, 0xe4, 0x7b, 0x51, 0x6a,
	0xc6, 0x77, 0xf8, 0x12, 0x79, 0x45, 0x94, 0xf2, 0x49, 0x67, 0xd6, 0x99, 0x1f, 0x84, 0x27, 0x7b,
	0x43, 0x86, 0x1b, 0xa9, 0xb6, 0xb7, 0xbe, 0x55, 0x7d, 0x06, 0x49, 0x1c, 0xa0, 0x81, 0x3d, 0xd7,
	0xa5, 0x78, 0xe5, 0x93, 0x2e, 0x54, 0x9e, 0xee, 0x0d, 0x19, 0x7f, 0x57, 0x42, 0xca, 0x67, 0x7d,
	0x8b, 0x1f, 0x2d, 0x7c, 0xeb, 0xa0, 0x91, 0xeb, 0x54, 0x16, 0x38, 0x40, 0xc3, 0xa4, 0x52, 0x8a,
	0xe7, 0xfa, 0xc1, 0x71, 0x6c, 0x0c, 0x71, 0x65, 0xe6, 0x12, 0x4c, 0x11, 0xd2, 0x52, 0x47, 0xd9,
	0x4a, 0x56, 0xb9, 0x6e, 0x9d, 0x47, 0x8d, 0x21, 0x8e, 0xca, 0x1c, 0x8c, 0x57, 0xc8, 0xcb, 0x44,
	0xa9, 0x27, 0xbd, 0x59, 0x6f, 0x3e, 0x5c, 0x5e, 0xd1, 0xdf, 0xcf, 0x45, 0x7f, 0xae, 0x44, 0x2d,
	0x08, 0xfb, 0x8d, 0x21, 0xd0, 0xc6, 0x20, 0x4e, 0x2f, 0x90, 0x67, 0x75, 0x7c, 0x8e, 0x7a, 0x85,
	0x48, 0x60, 0xcf, 0x41, 0x78, 0xd4, 0x18, 0x62, 0x29, 0xb3, 0x61, 0xf9, 0xfc, 0x79, 0x39, 0xd6,
	0xce, 0xc6, 0x77, 0x6d, 0x13, 0xf9, 0xdb, 0x73, 0x37, 0x9d, 0xfd, 0xb7, 0x54, 0xe8, 0x3d, 0x75,
	0xeb, 0x20, 0x3e, 0x84, 0x0f, 0xbb, 0x79, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x13, 0x0e, 0xde,
	0x0a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BannerResourceClient is the client API for BannerResource service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BannerResourceClient interface {
	// Query请求单个资源
	List(ctx context.Context, in *BannerListReq, opts ...grpc.CallOption) (*BannerListResp, error)
}

type bannerResourceClient struct {
	cc grpc.ClientConnInterface
}

func NewBannerResourceClient(cc grpc.ClientConnInterface) BannerResourceClient {
	return &bannerResourceClient{cc}
}

func (c *bannerResourceClient) List(ctx context.Context, in *BannerListReq, opts ...grpc.CallOption) (*BannerListResp, error) {
	out := new(BannerListResp)
	err := c.cc.Invoke(ctx, "/live.resource.v1.BannerResource/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BannerResourceServer is the server API for BannerResource service.
type BannerResourceServer interface {
	// Query请求单个资源
	List(context.Context, *BannerListReq) (*BannerListResp, error)
}

// UnimplementedBannerResourceServer can be embedded to have forward compatible implementations.
type UnimplementedBannerResourceServer struct {
}

func (*UnimplementedBannerResourceServer) List(ctx context.Context, req *BannerListReq) (*BannerListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterBannerResourceServer(s *grpc.Server, srv BannerResourceServer) {
	s.RegisterService(&_BannerResource_serviceDesc, srv)
}

func _BannerResource_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BannerListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerResourceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/live.resource.v1.BannerResource/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerResourceServer).List(ctx, req.(*BannerListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _BannerResource_serviceDesc = grpc.ServiceDesc{
	ServiceName: "live.resource.v1.BannerResource",
	HandlerType: (*BannerResourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _BannerResource_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "banner_resource.proto",
}
