// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_resource.proto

package v1

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 请求单个资源
type QueryReq struct {
	// 资源id
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryReq) Reset()         { *m = QueryReq{} }
func (m *QueryReq) String() string { return proto.CompactTextString(m) }
func (*QueryReq) ProtoMessage()    {}
func (*QueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f23b72a6a2080599, []int{0}
}

func (m *QueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryReq.Unmarshal(m, b)
}
func (m *QueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryReq.Marshal(b, m, deterministic)
}
func (m *QueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReq.Merge(m, src)
}
func (m *QueryReq) XXX_Size() int {
	return xxx_messageInfo_QueryReq.Size(m)
}
func (m *QueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReq proto.InternalMessageInfo

func (m *QueryReq) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

// 返回单个资源
type QueryResp struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResp) Reset()         { *m = QueryResp{} }
func (m *QueryResp) String() string { return proto.CompactTextString(m) }
func (*QueryResp) ProtoMessage()    {}
func (*QueryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f23b72a6a2080599, []int{1}
}

func (m *QueryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResp.Unmarshal(m, b)
}
func (m *QueryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResp.Marshal(b, m, deterministic)
}
func (m *QueryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResp.Merge(m, src)
}
func (m *QueryResp) XXX_Size() int {
	return xxx_messageInfo_QueryResp.Size(m)
}
func (m *QueryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResp proto.InternalMessageInfo

func (m *QueryResp) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *QueryResp) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *QueryResp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryReq)(nil), "live.resource.v1.QueryReq")
	proto.RegisterType((*QueryResp)(nil), "live.resource.v1.QueryResp")
}

func init() { proto.RegisterFile("user_resource.proto", fileDescriptor_f23b72a6a2080599) }

var fileDescriptor_f23b72a6a2080599 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x15, 0x97, 0x96, 0xd6, 0xea, 0x80, 0x8c, 0x84, 0x4a, 0x90, 0x48, 0xe4, 0x29, 0x0b,
	0xae, 0x0a, 0x4c, 0x9d, 0xaa, 0x3c, 0x01, 0x58, 0x62, 0x61, 0x41, 0x49, 0x7d, 0x4d, 0x2d, 0x35,
	0x38, 0x3d, 0xc7, 0x91, 0x78, 0xd9, 0x3c, 0x40, 0x46, 0x9e, 0x00, 0xc5, 0x2d, 0x19, 0x90, 0xd8,
	0xee, 0xbf, 0xfb, 0xfd, 0x59, 0xff, 0x4f, 0xaf, 0x9d, 0x05, 0xfc, 0x40, 0xb0, 0xc6, 0xe1, 0x16,
	0x44, 0x85, 0xa6, 0x36, 0xec, 0xea, 0xa0, 0x1b, 0x10, 0xc3, 0xb2, 0x59, 0x85, 0x0f, 0x85, 0xae,
	0xf7, 0x2e, 0x17, 0x5b, 0x53, 0x2e, 0x0b, 0x53, 0x98, 0xa5, 0x37, 0xe6, 0x6e, 0xe7, 0x95, 0x17,
	0x7e, 0x3a, 0x01, 0xf8, 0x86, 0x4e, 0x5f, 0x1d, 0xe0, 0x97, 0x84, 0x23, 0x7b, 0xa6, 0x23, 0xa7,
	0xd5, 0x22, 0x88, 0x83, 0x64, 0x9c, 0xf2, 0xef, 0x36, 0xba, 0xdf, 0x19, 0x2c, 0xd7, 0xdc, 0x69,
	0xc5, 0xe3, 0x26, 0x3b, 0x68, 0x95, 0xd5, 0xb0, 0xe6, 0x08, 0x47, 0xa7, 0x11, 0x14, 0x97, 0xbd,
	0x9d, 0xef, 0xe9, 0xec, 0x4c, 0xb0, 0x15, 0xbb, 0xa1, 0x64, 0x20, 0x4c, 0xba, 0x36, 0x22, 0x5a,
	0x49, 0xa2, 0x15, 0xbb, 0x3d, 0xa1, 0x89, 0x3f, 0x5c, 0x76, 0x6d, 0xd4, 0x4b, 0xff, 0x9e, 0x25,
	0x74, 0xda, 0x27, 0xfb, 0xcc, 0x4a, 0x58, 0x8c, 0xe2, 0x20, 0x99, 0xa5, 0xf3, 0xae, 0x8d, 0x86,
	0x9d, 0x1c, 0xa6, 0xc7, 0x17, 0x3a, 0x7f, 0xb3, 0x80, 0xf2, 0x9c, 0x96, 0x6d, 0xe8, 0xd8, 0xff,
	0xcc, 0x42, 0xf1, 0xb7, 0x06, 0xf1, 0x1b, 0x2a, 0xbc, 0xfb, 0xf7, 0x66, 0xab, 0xf4, 0xe2, 0x9d,
	0x34, 0xab, 0x7c, 0xe2, 0xab, 0x78, 0xfa, 0x09, 0x00, 0x00, 0xff, 0xff, 0x56, 0x57, 0xcf, 0x0c,
	0x62, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserResourceClient is the client API for UserResource service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserResourceClient interface {
	// Query请求单个资源
	Query(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryResp, error)
}

type userResourceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserResourceClient(cc grpc.ClientConnInterface) UserResourceClient {
	return &userResourceClient{cc}
}

func (c *userResourceClient) Query(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryResp, error) {
	out := new(QueryResp)
	err := c.cc.Invoke(ctx, "/live.resource.v1.UserResource/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserResourceServer is the server API for UserResource service.
type UserResourceServer interface {
	// Query请求单个资源
	Query(context.Context, *QueryReq) (*QueryResp, error)
}

// UnimplementedUserResourceServer can be embedded to have forward compatible implementations.
type UnimplementedUserResourceServer struct {
}

func (*UnimplementedUserResourceServer) Query(ctx context.Context, req *QueryReq) (*QueryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}

func RegisterUserResourceServer(s *grpc.Server, srv UserResourceServer) {
	s.RegisterService(&_UserResource_serviceDesc, srv)
}

func _UserResource_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserResourceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/live.resource.v1.UserResource/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserResourceServer).Query(ctx, req.(*QueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserResource_serviceDesc = grpc.ServiceDesc{
	ServiceName: "live.resource.v1.UserResource",
	HandlerType: (*UserResourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _UserResource_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_resource.proto",
}
